#!/usr/bin/env python3
"""Generate the example corpora from one source.

The variants exist to be a controlled experiment. Documents and probes are
identical across all four; only the navigation surface changes. Any difference
in score is therefore attributable to the index and nothing else.

Generated rather than hand-maintained so the variants cannot drift apart, which
would quietly destroy the control.
"""
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "source"

VARIANTS = {
    # name              index file            what it demonstrates
    "human-index":    ("index-human.md",     "reads well to a person, routes badly"),
    "retrieval-index": ("index-retrieval.md", "same docs, indexed with the words people ask in"),
    "stuffed-index":  ("index-stuffed.md",   "gamed: probe vocabulary dumped in, describes nothing"),
    "no-index":       (None,                 "no index at all, file tree is the surface"),
}


def build() -> None:
    for name, (index, _) in VARIANTS.items():
        out = ROOT / name
        if out.exists():
            shutil.rmtree(out)
        shutil.copytree(SRC / "docs", out / "docs")
        if index:
            shutil.copy(SRC / index, out / "index.md")
        shutil.copy(SRC / "questions.json", out / "questions.json")

    lines = ["# Example corpora", "",
             "Generated by `build.py`. Do not edit in place, edit `source/` and rebuild.", "",
             "Same six documents and the same nineteen hand-written probes in every",
             "variant. Only the navigation surface differs, so any score difference",
             "between them is caused by the index alone.", "",
             "| Variant | Surface | Demonstrates |", "|---|---|---|"]
    for name, (index, why) in VARIANTS.items():
        lines.append(f"| `{name}` | {'`index.md`' if index else 'file tree'} | {why} |")
    lines += ["",
              "## What each is for", "",
              "`human-index` and `retrieval-index` are the before and after of the",
              "finding this tool exists to measure. Identical content, very different",
              "reachability.", "",
              "`stuffed-index` is the adversary. It should score well lexically and",
              "flat semantically, and the run should emit a keyword-stuffing warning.",
              "If a change ever lets this corpus pass clean, the change is wrong.", "",
              "`no-index` exercises the implicit-surface path, where the file tree is",
              "scored as the index.", ""]
    (ROOT / "README.md").write_text("\n".join(lines), encoding="utf-8")

    n = len(json.loads((SRC / "questions.json").read_text())["probes"])
    docs = len(list((SRC / "docs").glob("*.md")))
    for name in VARIANTS:
        print(f"  built examples/{name}  ({docs} docs, {n} probes)")


if __name__ == "__main__":
    build()
